# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-BulkLoader-Mysql
version:      0.03
version_from: lib/DBIx/BulkLoader/Mysql.pm
installdirs:  site
requires:
    DBD::mysql:                    2.9006
    DBI:                           1.53

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
